pkg/cmd/server/server.go
Fix the new schemas location in `server.go` 
=> fix path to the schemas location

pkg/cmd/server/server.go, pkg/common/convert.go, pkg/ovsdb/handler.go, pkg/ovsjson/types.go
remove unused server loop function, change `columns` type to strings
=> Cleanup: serverLoop, collumns -> strings

pkg/libovsdb/encoding_test.go
=> rename compareJsonMapSets to compareJSONMapSets

pkg/libovsdb/notation.go, pkg/ovsdb/transact.go
When `OperationResult` contains the `UUID` field  as type `UUID`, which is struct, despite on the `omitempty` tag, json prints empty structs when the filed is not set. OVSDB clients don't like it ;-)
The _uuid collomn has type UUID and not string 
=> Fix uuid type, prevent print empty UUIDs

pkg/libovsdb/schema.go, pkg/ovsdb/transact_test.go
=> Fix `panic: nil base type` for Set validation

pkg/ovsdb/handler.go, pkg/ovsdb/transact.go
insert:
```
=== RUN   TestTransactAtomicInsertNamedUUID
I0604 16:57:55.067222    8461 transact.go:576] etcd: monitor events [{Type:PUT Kv:key:"ovsdb/nb/atomic/table1/00000000-0000-0000-0000-000000000001" version:1 value:"{\"_uuid\":[\"uuid\",\"00000000-0000-0000-0000-000000000001\"],\"boolean\":false,\"integer\":0,\"real\":0,\"string\":\"val1\",\"uuid\":[\"uuid\",\"00000000-0000-0000-0000-000000000000\"]}"  PrevKv:<nil> XXX_NoUnkeyedLiteral:{} XXX_unrecognized:[] XXX_sizecache:0} {Type:PUT Kv:key:"ovsdb/nb/atomic/table1/00000000-0000-0000-0000-000000000001" value:"{\"_uuid\":[\"uuid\",\"00000000-0000-0000-0000-000000000001\"],\"boolean\":false,\"integer\":0,\"real\":0,\"string\":\"val1\",\"uuid\":[\"uuid\",\"00000000-0000-0000-0000-000000000001\"]}" …
```
=> txn: create monitor events

dist/images/Dockerfile.etcd
this pr adds `ovnkube.sh` execution permissions
this PR related to the PR on `OVN` fork here:
https://github.com/IBM/ovn-kubernetes/pull/1
=> adding tcpdump logging [WIP]

pkg/ovsdb/database.go, pkg/ovsdb/database_test.go, pkg/ovsdb/handler.go, pkg/ovsdb/monitor.go, pkg/ovsdb/monitor_test.go, pkg/ovsdb/service.go
Initial monitor data should be fetched as a single transaction operation, which prevents inconsistency of returned data.
Fix send notification synchronization wait.
=> Add etcd transactions to getMonitor data

pkg/ovsdb/handler.go, pkg/ovsdb/monitor.go
According to [ovsdb-server.7](https://docs.openvswitch.org/en/latest/ref/ovsdb-server.7/#monitor-cond-change), the monitor-cond-change request should return
> The response object has the following members:
"result": null
"error": null
"id": same "id" as request
However, when result is null, or missing the client (ovn-controller) returns the following misleading message :
> jsonrpc|WARN|tcp:172.18.0.4:6642: received bad JSON-RPC message: request must have "method"
2021-06-07T14:32:30.116Z|00027|reconnect|WARN|tcp:172.18.0.4:6642: connection dropped (Protocol error)
and closes connection ;-(
This PR fixes it. 
/fix #201
=> Fix bad JSON-RPC message

pkg/ovsdb/transact.go
Without this fix is very hard to separate prints of current KV from prevKV
=> Fix etcd events print

pkg/ovsdb/handler.go, pkg/ovsdb/monitor_test.go
This PR continues https://github.com/IBM/ovsdb-etcd/pull/248 testing of `monitor_test.go` and fixing the tests:
- `TestMonitorNotifications1`
- `TestMonitorNotifications2`
- `TestMonitorNotifications3`
- `TestMonitorAddRemoveMonitor`
=> Add map/set processing for update rows with updated `monitor test`

pkg/cmd/server/server.go, pkg/ovsdb/handler.go, pkg/ovsdb/monitor.go, pkg/ovsdb/monitor_test.go, pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go, tests/e2e/e2e_test.go
OVSDB requires that after transaction execution, the client gets the monitor notification and only after that the transaction response.
We had a race confition between notification created by transactions and etcd watch notifications. This PR resolves it.
=> Race condition between notifciations and transaction return

pkg/ovsdb/handler.go
`monitorCanceledNotification` can fail because a client has closed its connection first. We don't have to inform it as an error.
=> Change 'monitorCanceledNotification failed' log level

pkg/ovsdb/condition.go, pkg/ovsdb/handler.go, pkg/ovsdb/monitor.go, pkg/ovsdb/monitor_test.go, pkg/ovsjson/encode_test.go, pkg/ovsjson/types.go
This PR is adding support "Where" flag in conditional monitoring.it comes into play mainly on `updater` method called `prepareRow`.
The types I covered on the tests are: `Int`,`float64` (a.k.a in `ovs` terms :`real`),`UUID`,`string`,`bool` and the types still need to cover are: `map` , `set` and `Enum`.
when using `prepareRow` we eventually calling `NewCondition` (the call hierarchy: `prepareRow`->`isRowAppearOnWhere`->`NewCondition`). 
```go
func NewCondition(tableSchema *libovsdb.TableSchema, mapUUID MapUUID, condition []interface{}, log logr.Logger) (*Condition, error)
```
Notice that one of `NewCondition` parameters is `log logr.Logger`. Neither `prepareRow` parameters nor `updater` have access to a logger. Currently I creating a mock logger to avoid `nil` de referencing on …
=> Support "Where" flag in conditional monitoring

go.mod, go.sum, pkg/cmd/server/server.go, pkg/common/key.go, pkg/libovsdb/map.go, pkg/libovsdb/notation.go, pkg/libovsdb/schema.go, pkg/libovsdb/set.go, pkg/ovsdb/cache.go, pkg/ovsdb/condition.go, pkg/ovsdb/condition_test.go, pkg/ovsdb/database.go, pkg/ovsdb/handler.go, pkg/ovsdb/monitor.go, pkg/ovsdb/monitor_test.go, pkg/ovsdb/mutation.go, pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go
Originally, most of OVSDB transaction operations were implemented as 2 etcd transactions: fetch data, process it, and store the data back in etcd.
The cache rids off the first transactions. 
Plus added an optimization for transactions that contain an explicit _uuid selector.
=> Add permonent cache and remove the first Trx

pkg/ovsdb/cache.go, pkg/ovsdb/database.go, pkg/ovsdb/handler.go, pkg/ovsdb/monitor.go, pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go
Add mutex Lock/RLock to protect handler's monitor related maps `monitors` and `handlerMonitorData`.
`databaseLocks` implements as a sync.Map.
Add locks to cache and schemas
=> Prevet concurrent modification of Handler's internal maps

pkg/ovsdb/monitor.go
Now when we have callback functions, we don't need the notifier sleep
=> remove sleep from notifier

pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go
Originally we ran all data modification operations under a relevant table lock, which reduced the system throughput. 
This PR removes insert operations from the table lock, and add unexistence condition to the etcd transaction operation.
=> Remove insert operations from tables lock

pkg/ovsdb/transact.go
When we get the concurrency error, we run another attempt. This PR fixes the ovsdb transaction reset before running this second attempt.
=> Fix reset ovsdb trx before run the second etcd trx attempt

pkg/ovsdb/monitor.go, pkg/ovsdb/monitor_test.go
ovsdb-etcd profiling showed that the setsDifference  function uses a lot of CPU. This PR reimplements it to provide a more efficient implementation.
=> reimplementation of the setsDifference function

pkg/ovsdb/transact.go
increase the number of attempts to resolve concurrency error from 5 to 10, and increase the sleep interval between the iterations.
=> Increase transaction iteration number

pkg/libovsdb/row.go, pkg/ovsdb/cache.go, pkg/ovsdb/database.go, pkg/ovsdb/monitor.go, pkg/ovsdb/monitor_test.go
All monitors have to prepare a row (unmarshal row data from JSON to goLang object). This PR implements shared prepareRow for all monitors.
=> Common prepare row for all monitors

pkg/libovsdb/notation.go, pkg/ovsdb/condition.go, pkg/ovsdb/condition_test.go, pkg/ovsdb/handler.go, pkg/ovsdb/monitor.go, pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go
Some of OVNk transaction requests have "Where" entry with selection of a single row by "indexed columns". In this case, we don't need to lock the entire table, and can operate over a specific key only.
The PR adds this optimization. 
=> add select single row by index

pkg/common/key.go, pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go
Comments cannot be parsed into libovsdb.Row, and they should not be propagated to monitor, and transaction cache, so we put them into a separate tree. (locks were there before)
=> Put comments into a separate key-tree

pkg/cmd/server/server.go, pkg/ovsdb/monitor.go
When a client closed its connection to the ovsdb-etcd server, the latter printed a Server error message, that was misleading. 
The PR changed this behaviour to print an info message instead of error.
Signed-off-by: Alexey Roytman roytman@il.ibm.com
=> Server error

pkg/ovsdb/monitor.go
fix log message for monitor when `uuid != prevUUID`
=> fix log message for

pkg/cmd/server/server.go, pkg/ovsdb/cache.go, pkg/ovsdb/database.go, pkg/ovsdb/handler.go, pkg/ovsdb/service.go
Data in the _Server database is per-server and should not be stored in etcd and shared between all servers. This PR fixes it.
=> Store _Server/Databases data locally

pkg/cmd/server/server.go, pkg/ovsdb/database.go, pkg/ovsdb/service.go
Some of the entries in the _Server database were not correctly implemented. 
They are:
-  `cid` - the cluster id and it should be shared between all servers
- `sid` - the given server id, which should be returned by `get_server_id` request
This PR fixes these issues.
=> Implement clusterID

pkg/cmd/server/server.go
Some of the executable scripts, e.g. ovn heater use the `loadServerDataFlag` flag, we temporarily returned the flag here to allow the scripts to run.
Later, after updating the scripts, the flag will be removed 
=> Return back loadServerDataFlag flag for backward compatability

pkg/ovsdb/cache.go, pkg/ovsdb/handler.go, pkg/ovsdb/transact.go
Replace Locks to Rlocks to the read-only operations from the cache.
=> Replace Locks to RLocks to the read from cache operations

pkg/libovsdb/row.go, pkg/libovsdb/schema.go, pkg/ovsdb/cache_test.go, pkg/ovsdb/condition.go, pkg/ovsdb/condition_test.go, pkg/ovsdb/database.go, pkg/ovsdb/handler.go, pkg/ovsdb/monitor.go, pkg/ovsdb/monitor_test.go, pkg/ovsdb/mutation.go, pkg/ovsdb/service.go, pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go
Some of the constants were named according to "C" code convention "SOME_CONST". 
Here they were renamed according to Golang convention - "SomeConst"
=> Rename constants according to GoLang convention

pkg/ovsdb/transact.go
When etcd transaction fails and ovsdb-etcd server resends it, the `namedUUIDResolver` should be reset, otherwise we might get "duplicate uuid-name"
=> Fix duplicate uuid-name error

pkg/cmd/server/server.go, pkg/ovsdb/cache.go, pkg/ovsdb/cache_test.go, pkg/ovsdb/database.go, pkg/ovsdb/database_test.go, pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go
Rollbacks context settings from one of previous PRs, and fixes  "context close" error.
Fixes  "duplicate IP" error
=> rollback context changes

.gitignore, pkg/cmd/client/client.go, pkg/cmd/server/server.go, pkg/cmd/ssl_utils/ssl-util.go, tests/e2e/Makefile
This PR adds ssl support for the client and the server.
using `tests/e2e/Makefile` one can:
1. create and delete ssl keys for the server and the client.
2. deploy client and server with or without ssl.
3. call ovsdb-client with ssl.
client cannot configure specific cipher suite when using TLS3.(as seen on `tls` package)
```go
type Config struct {
.
.
.
// CipherSuites is a list of enabled TLS 1.0–1.2 cipher suites. The order of
// the list is ignored. Note that TLS 1.3 ciphersuites are not configurable.
//
// If CipherSuites is nil, a safe default list is used. The default cipher
// suites might change over time.
CipherSuites []uint16
.
.
.
}
```
the following commands should be executed from the root directory.
make keys for the client and the server
```bash
make -C tests/e2e/ …
```
=> SSL support

pkg/libovsdb/notation.go, pkg/ovsdb/database.go, pkg/ovsdb/database_test.go, pkg/ovsdb/handler.go, pkg/ovsdb/handler_test.go, pkg/ovsdb/lock.go, pkg/ovsdb/transact.go, pkg/ovsdb/transact_test.go
- Add unit tests for OVSDB locking operations, 
- implement transaction "Assert" operation 
=> Fix locking operations
