IBM/ovsdb-etcd

Makefile

Add client rule to the Makefile

---

go.mod
go.sum
pkg/json/encode_test.go
pkg/json/types.go

Add types from  libovsdb

---

pkg/ovsdb/db_server.go

Compact Schemas

---

pkg/cmd/client/client.go
pkg/cmd/server/server.go
pkg/ovsdb/ovsdb.go

Cange OVSDB methods according to the Golang convention

---

pkg/json/types.go
pkg/ovsdb/ovsdb.go

Small fixes in the Monitor methods

---

pkg/ovsdb/database.go

Cnange GetData request to bring data WithPrefix

---

go.mod
go.sum
pkg/common/convert.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/service_test.go
pkg/ovsjson/encode_test.go
pkg/ovsjson/types.go
tests/data/monitor/monitor-data.json

Adds tests for initial data returned by the monitor functions

Adds tests for initial data returned by the monitor functions

---

pkg/cmd/server/server.go
pkg/cmd/server/testdata.go
pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/operation.go
pkg/ovsdb/service.go

Add configurable etcd keys prefix

---

pkg/cmd/server/server.go
pkg/common/convert.go
pkg/ovsdb/database.go
pkg/ovsdb/database_test.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/service_test.go

Implement Lock and Unlock

---

pkg/cmd/server/testdata.go

fix segmentation violation

---

pkg/cmd/server/server.go
pkg/ovsdb/handler.go

fix locking

---

go.mod
pkg/ovsdb/handler.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/monitors.go

Add prepareTableUpdate and its tests

---

pkg/libovsdb/encoding_test.go
pkg/libovsdb/notation.go
pkg/libovsdb/notation_test.go
pkg/libovsdb/set.go

Add single emelemnt set support, fix maps compare

---

pkg/cmd/server/testdata.go

Fix table name copy/paste typo 

---

pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/monitors.go

[WIP] Global monitors

---

pkg/libovsdb/client.go
pkg/libovsdb/notation.go
pkg/libovsdb/rpc_test.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitors.go
pkg/ovsjson/encode_test.go

Change MonitorSelect object to separate unset and false values

---

pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/monitors.go

Global monitors

---

Makefile
tests/e2e/Makefile

Fix binding address

---

pkg/generator/generator.go
pkg/types/OVN_Northbound/types.go
pkg/types/OVN_Southbound/types.go
pkg/types/_Server/types.go

Fix uuid in the generated types

---

pkg/ovsdb/handler.go

Fix transaction response

---

pkg/common/key.go
pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/monitors.go
pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

unify get Initial rows

---

pkg/cmd/server/testdata.go

Fx test data

---

pkg/ovsdb/handler.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/monitors.go

fix jsonValue

---

pkg/cmd/server/server.go

Add OVSDB functions map

---

pkg/cmd/server/server.go
pkg/cmd/server/testdata.go
tests/e2e/Makefile

Separation of load schema to server(s) configuration `_Server` and loading the test data

Server init

---

pkg/ovsdb/transact.go

fix klog import

---

Makefile
dist/ovn-kubernetes/dist/images/ovnkube.sh
pkg/cmd/server/server.go

Add last commit info

---

dist/ovn-kubernetes/dist/images/ovnkube.sh
dist/ovn-kubernetes/dist/templates/ovnkube-db.yaml.j2
go.mod
go.sum
pkg/cmd/generator/generator.go
pkg/common/convert.go
pkg/generator/generator.go
pkg/ovsdb/database.go
pkg/ovsdb/monitors.go
pkg/ovsdb/service.go

change klog to klogv2, add logLevel env variable

---

pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsjson/encode.go

Allow CondMonitorParameters without JsonValue

---

pkg/ovsjson/encode.go

Fix CondMonitorParameters JSON unmarshalling

---

go.mod
go.sum

JRPCv1 error response contains only the error message, without error code. 
Update the JRPC implementation to return error according to the protocol

change jrpc package

---

pkg/cmd/server/server.go
pkg/common/file.go
pkg/libovsdb/schema.go
pkg/ovsdb/database.go
pkg/ovsdb/database_test.go
pkg/ovsdb/service.go

Store original schemas

---

pkg/ovsdb/handler.go
pkg/ovsdb/transact.go

Add logs, fix uuid transformation

---

pkg/ovsdb/transact.go

Fix comaprison in the wait operation

---

dist/ovn-kubernetes/dist/images/ovnkube.sh
dist/ovn-kubernetes/dist/templates/ovnkube-db.yaml.j2
pkg/libovsdb/notation.go
pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go
pkg/ovsjson/types.go

Add print of transaction results

---

pkg/ovsdb/handler.go

Fix empty lines in the monitored data

---

Makefile
dist/ovn-kubernetes/dist/templates/ovnkube-node.yaml.j2

Temporary solution, until the [PR 2233](https://github.com/ovn-org/ovn-kubernetes/pull/2233) will be accepted by the upstream OVNk community

Fix ovn-controller log level

---

pkg/ovsdb/transact.go

Increase etcd client message size limits

---

pkg/ovsdb/database.go
pkg/ovsdb/transact.go

Move NewEtcdClient to database.go

---

pkg/ovsdb/handler.go
pkg/ovsjson/encode.go
pkg/ovsjson/encode_test.go
pkg/ovsjson/types.go

Fix json-value

---

pkg/common/key.go

Fix table key

---

Makefile
dist/README.md

Small fixes

---

pkg/ovsdb/handler.go
pkg/ovsdb/transact.go

Add logs to monitor methods

---

Makefile

Add ovnk-delete

---

go.mod
pkg/ovsdb/database.go

Remove zapLogger

---

pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go

*  refactor for the test `TestAddRemoveUpdaters` this PR split it into 4 different testing scenarios
*  adding basic test that create a simple handler and add a monitor for it. `TestHandlerAddMonitor`

Monitor testing

---

pkg/ovsdb/handler.go

Fix getMonitoredData add unittest

---

pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/transact.go

Add etcd notification revision checker

---

pkg/ovsdb/handler.go

Add remote address to log messages

---

go.mod
go.sum
pkg/cmd/server/server.go
pkg/ovsdb/handler.go
pkg/ovsdb/service.go

Add connection wrapper, add prints

---

pkg/cmd/server/server.go
pkg/ovsdb/monitor.go

Fixes handlers mismatching and as result the "duplicate monitor ID" and client's disconnects issues 

Fix handlers mismatching

---

pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/transact.go

Global transaction lock

---

Makefile
dist/README.md

Corresponding PR on the OVN repository:
https://github.com/IBM/ovn-kubernetes/pull/2

adding tcpdump flag control

---

go.mod
go.sum
pkg/ovsdb/transact.go

make verify on PR by @hunchback :
https://github.com/IBM/ovsdb-etcd/pull/209

 txn: fix klogr output (after make verify)

---

pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go

Add queue to monitors

---

pkg/cmd/server/server.go

Remove debug.PrintStack()

---

pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

Revert "txn: remove default values"

---

pkg/cmd/server/server.go
tests/e2e/Makefile

Revert "server: use klogr logging"

---

pkg/ovsdb/database.go
pkg/ovsdb/monitor.go

Add wg.Done when there is no monitors to notify

---

pkg/ovsdb/monitor.go

fix invalid memory address or nil pointer dereference

---

pkg/ovsdb/monitor.go

add prints, defer wg.done

---

pkg/ovsdb/monitor.go

small print fix

---

pkg/ovsdb/monitor.go

fix info message

---

Makefile

add original ovnk deployment

---

pkg/ovsdb/transact.go

I will post follow-ups to this:
- good printout of events
- tests analyzing that events generated are correct

txn: copy row before update/mutate

---

pkg/common/key.go
pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go

Add map/set processing for update rows

---

pkg/ovsdb/monitor.go

The "update" notification (notification of "monitor" request) conatis entire set/map values in the "old" filed.

Update 'old' value of modified sets and maps

---

pkg/ovsdb/monitor_test.go

resolve conflict

---

pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go

Add revision to monitoring prints

---

pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

@roytman - this is a test for issue #259 - but it passes ... can you check?

txn: mutate map delete+insert

---

pkg/libovsdb/schema.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go
pkg/ovsjson/encode_test.go
pkg/ovsjson/types.go

Support empty array of strings.
Fix monitoring tests

support Columns[]

---

pkg/libovsdb/schema.go
pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

Revert "Txn refcount"

---

pkg/libovsdb/schema.go
pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

Revert "txn: implement strong ref"

---

pkg/ovsdb/monitor.go

return modify message of single element set as an element

---

Makefile
scripts/ovnkube-logs.sh

do not run tcpdump by default

---

pkg/ovsdb/handler.go

prevent transactional deadlock

---

pkg/ovsdb/database.go
pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

remove unused methods
move etcd event print-related methods to database.go
allow combinations of "Select" and data unmodified operations
extend `TestTransactComment` to check the comment data
add utittest with combination of `Select` and `Comment`

Trx cleanup

---

Makefile

update etcd to v3.5.0

---

pkg/ovsdb/condition.go
pkg/ovsdb/mutation.go
pkg/ovsdb/transact.go

separation of Mutation and Condition

---

pkg/ovsdb/condition.go
pkg/ovsdb/mutation.go
pkg/ovsdb/transact.go

Put the log argument as the last one

---

pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go

Add logger to updaters

---

pkg/cmd/server/server.go

Signed-off-by: Mohamed S. Mahmoud <mmahmoud@redhat.com>
Add cpuprofile logs to use it :-
```
1- kill -SIGTERM <pid>
2- go tool pprof <cpuprof file>
```

Add cpuprofile option to be used with go tool pprof

---

pkg/ovsdb/transact.go

Combine Select and Delete operations

---

pkg/ovsdb/transact.go

eliminate etcdThen update methods

---

pkg/ovsdb/monitor.go
pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

Fix returned counter of Update & Mutate operations

---

pkg/ovsdb/transact_test.go

add a unitTest for returned counter

---

pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

optimize code of the doModify operation

---

README.md

fix comments path

---

pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go

fix concurrent map access

---

pkg/ovsdb/monitor.go

increase start notification timeout from 5 to 20 ms

---

pkg/cmd/server/server.go
pkg/ovsdb/database.go

add etcd client keepalive-timeout flags

---

pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

Add V() level to logs

---

pkg/ovsdb/handler.go

protecte by lock ch.handlerMonitorData

---

pkg/ovsdb/monitor.go

remove log messages and prevent NP panic

---

pkg/ovsdb/handler.go

remove handler.mu.Lock from the handler lock operation

---

pkg/ovsdb/cache.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/transact_test.go

Add lock protection to dataCache operations

---

pkg/libovsdb/map.go
pkg/libovsdb/set.go
pkg/ovsdb/condition.go
pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/mutation.go
pkg/ovsdb/transact.go

Support "Where" flag in conditional monitoring for set and map types

---

go.mod
go.sum
pkg/ovsdb/handler.go

fixing monitoring syncing issue

fixing monitoring syncing issue

---

pkg/ovsdb/handler.go
pkg/ovsdb/transact.go

Remove delete operations from the tables lock

---

pkg/ovsdb/handler.go
pkg/ovsdb/transact.go

Add etcd transaction debug message

---

pkg/ovsdb/transact.go

When we get the concurrency error, we run another attempt. This PR fixes the ovsdb transaction reset before running this second attempt.

remove tables lock from Insert and mutate operations

---

pkg/cmd/server/server.go
pkg/common/file.go
pkg/common/key.go
pkg/ovsdb/cache.go
pkg/ovsdb/condition.go
pkg/ovsdb/database.go
pkg/ovsdb/handler.go
pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go
pkg/ovsdb/mutation.go
pkg/ovsdb/service.go
pkg/ovsdb/transact.go
pkg/ovsdb/transact_test.go

Fix spelling typos, unhandled possible  errors, and other warnings.

Cleanup spelling and code validation warnings

---

pkg/ovsdb/database.go
pkg/ovsdb/transact.go

add logs to etcd failures, add sleep to trx

---

pkg/ovsdb/database.go
pkg/ovsdb/handler.go

Originally getMonitoredData returned data from etcd, now when ovsdb-etcd servers
have internal cache, the method returns data from the cache.

Returns getMonitoredData from cache

---

pkg/ovsdb/monitor.go
pkg/ovsdb/monitor_test.go

Add more log messages to the etcd2ovsdbEvent method

add log messages to etcd2ovsdbEvent

---

pkg/ovsdb/monitor.go

`Condition monitoring` messages include the `Where` field, which filters returned notifications. 
This PR fixes the use case when an original value of a database row did not meet the `Where` conditions, after that the value was modified ao it met the condition, and finally it was modified again to the condition was not met again.

add notification processing with 'Where'

---

pkg/ovsdb/transact.go
pkg/types/OVN_Northbound/types.go
pkg/types/OVN_Southbound/types.go
schemas/_server.ovsschema
schemas/ovn-nb.ovsschema
schemas/ovn-sb.ovsschema

The schema files were updated accoring to the latest OVN/OVS versions

Update OVN schemas

---

pkg/ovsdb/transact_test.go

Add a transaction test when the same transaction contains a delete row operation and insert a new row with the same name.

Add transaction test with delete-insert operation

---

pkg/ovsdb/transact.go

Replace Lock by Rlock for transaction proessing

---

pkg/ovsdb/handler.go

Revert "Change timestamps log message to level 4"

---

pkg/cmd/server/server.go
pkg/ovsdb/database.go
pkg/ovsdb/database_test.go
pkg/ovsdb/handler.go
pkg/ovsdb/transact.go

Revert "Provide an option that all ovsdb-servers works as leaders. [WIP]"
